/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QrWhatsappRouteImport } from './routes/qr-whatsapp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTermometroRouteImport } from './routes/_app.termometro'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPainelRouteImport } from './routes/_app.painel'
import { Route as AppKanbanRouteImport } from './routes/_app.kanban'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'

const QrWhatsappRoute = QrWhatsappRouteImport.update({
  id: '/qr-whatsapp',
  path: '/qr-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTermometroRoute = AppTermometroRouteImport.update({
  id: '/termometro',
  path: '/termometro',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPainelRoute = AppPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qr-whatsapp': typeof QrWhatsappRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/kanban': typeof AppKanbanRoute
  '/painel': typeof AppPainelRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/termometro': typeof AppTermometroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/qr-whatsapp': typeof QrWhatsappRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/kanban': typeof AppKanbanRoute
  '/painel': typeof AppPainelRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/termometro': typeof AppTermometroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/qr-whatsapp': typeof QrWhatsappRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/painel': typeof AppPainelRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/termometro': typeof AppTermometroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/qr-whatsapp'
    | '/configuracoes'
    | '/kanban'
    | '/painel'
    | '/relatorios'
    | '/termometro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/qr-whatsapp'
    | '/configuracoes'
    | '/kanban'
    | '/painel'
    | '/relatorios'
    | '/termometro'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/qr-whatsapp'
    | '/_app/configuracoes'
    | '/_app/kanban'
    | '/_app/painel'
    | '/_app/relatorios'
    | '/_app/termometro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  QrWhatsappRoute: typeof QrWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qr-whatsapp': {
      id: '/qr-whatsapp'
      path: '/qr-whatsapp'
      fullPath: '/qr-whatsapp'
      preLoaderRoute: typeof QrWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/termometro': {
      id: '/_app/termometro'
      path: '/termometro'
      fullPath: '/termometro'
      preLoaderRoute: typeof AppTermometroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/painel': {
      id: '/_app/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AppPainelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppKanbanRoute: typeof AppKanbanRoute
  AppPainelRoute: typeof AppPainelRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTermometroRoute: typeof AppTermometroRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppKanbanRoute: AppKanbanRoute,
  AppPainelRoute: AppPainelRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTermometroRoute: AppTermometroRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  QrWhatsappRoute: QrWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
